name: ddp_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  auto_size_text: 3.0.0
  animate_do: ^2.1.0
  carousel_slider: 4.0.0
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

#   FontWeight.w100: 'Thin',
#   FontWeight.w200: 'ExtraLight',
#   FontWeight.w300: 'Light',
#   FontWeight.w400: 'Regular',
#   FontWeight.w500: 'Medium',
#   FontWeight.w600: 'SemiBold',
#   FontWeight.w700: 'Bold',
#   FontWeight.w800: 'ExtraBold',
#   FontWeight.w900: 'Black',

flutter: 
  assets: 
    - assets/images/
    - assets/data/
  
  fonts: 
    - family: NotoSerifSC
      fonts: 
        - asset: assets/google_fonts/NotoSerifSC-ExtraLight.ttf
          weight: 100
        - asset: assets/google_fonts/NotoSerifSC-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/NotoSerifSC-Light.ttf
          weight: 300
        - asset: assets/google_fonts/NotoSerifSC-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/NotoSerifSC-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/NotoSerifSC-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/NotoSerifSC-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/NotoSerifSC-Black.ttf
          weight: 800
        - asset: assets/google_fonts/NotoSerifSC-Black.ttf
          weight: 900
          
  uses-material-design: true

