name: ddp_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  auto_size_text: 3.0.0
  carousel_slider: 4.0.0
  responsive_framework: 0.1.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: NotoSansSC
      fonts: 
        - asset: assets/google_fonts/NotoSansSC-Thin.otf
          weight: 100
        - asset: assets/google_fonts/NotoSansSC-Thin.otf
          weight: 200
        - asset: assets/google_fonts/NotoSansSC-Light.otf
          weight: 300
        - asset: assets/google_fonts/NotoSansSC-Regular.otf
          weight: 400
        - asset: assets/google_fonts/NotoSansSC-Medium.otf
          weight: 500
        - asset: assets/google_fonts/NotoSansSC-Medium.otf
          weight: 600
        - asset: assets/google_fonts/NotoSansSC-Bold.otf
          weight: 700
        - asset: assets/google_fonts/NotoSansSC-Black.otf
          weight: 800
        - asset: assets/google_fonts/NotoSansSC-Black.otf
          weight: 900
          
  uses-material-design: true

